name: funny comment
on:
  issues: 
    types:[opened]
  
  workflow_dispatch:

jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add funny comment
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with: 
          GITHUB_TOKENT: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKENT: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
